### PR TITLE
Hongsu's updates

### PR DESCRIPTION
**Pull request by sudoghut**
1. Updated tgaz/tgw/webservice/index.html.

2. Downloaded some files from CDN to the  project age. The reason is that 1) some cdn doesn't support https; 2) google js cdn can be accessed from Mainland China.

3. Fixed some bugs.

### CODE REVIEW

**Comment by sudoghut** [comment]
4. update "To search place names CLICK HERE." to index.html

**Comment by vajlex** [comment]
very cool.  for some reason this image file is missing:
http://maps.cga.harvard.edu/tgaz/js/images/
I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

**Comment by vajlex** [comment]
very cool.  for some reason this image file is missing:
http://maps.cga.harvard.edu/tgaz/js/images/
I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

**Comment by vajlex** [comment]
very cool.  for some reason this image file is missing:
http://maps.cga.harvard.edu/tgaz/js/images/
I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

**Comment by vajlex** [comment]
very cool.  for some reason this image file is missing:
http://maps.cga.harvard.edu/tgaz/js/images/
I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

**Comment by vajlex** [comment]
very cool.  for some reason this image file is missing:
http://maps.cga.harvard.edu/tgaz/js/images/
I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

**Comment by sudoghut** [comment]
> very cool. for some reason this image file is missing:
> http://maps.cga.harvard.edu/tgaz/js/images/
> I think if you are not using the cdn, you need to get the image and store locally (in the folder above).

Aha, this folder is accessible on my side :) Maybe you can forcefully refresh the directory
image

**Pull request closed without merging**
